name: Bug report
description: Report something that isn’t working
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the details below.
  - type: input
    id: component
    attributes:
      label: Component
      description: App / Website / Other
      placeholder: App
    validations:
      required: true
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: What did you see? What did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs or add screenshots if you can.
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: Windows 11
    validations:
      required: false

