"use client";

const steps = [
  "Open Modrinth App",
  "Click Add Instance",
  "Click Import from file",
  "Select your downloaded pack",
  "Launch Minecraft",
];

export default function ModrinthInstructions() {
  return (
    <section id="pure-import" className="full-width-section relative overflow-hidden py-20">
      <div className="section-background">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(46,242,162,0.1),transparent_45%)]" />
      </div>
      <div className="section-content mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="relative overflow-hidden rounded-[32px] border border-white/10 bg-[#0d1117]/90 p-6 shadow-[0_18px_80px_rgba(0,0,0,0.38)] sm:p-8 lg:p-10">
          <div className="absolute inset-x-10 top-0 h-px bg-gradient-to-r from-transparent via-accent/70 to-transparent" />
          <div className="grid gap-8 lg:grid-cols-[0.92fr_1.08fr] lg:items-center">
            <div className="space-y-4">
              <p className="text-xs font-mono uppercase tracking-[0.32em] text-accent/80">
                Modrinth Import
              </p>
              <h2 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl">
                Built for Modrinth. Designed for simplicity.
              </h2>
              <p className="max-w-xl text-base text-text-secondary sm:text-lg">
                Once your config is downloaded, importing it into Modrinth should feel
                as clean as the builder itself.
              </p>
              <div className="rounded-2xl border border-accent/20 bg-accent/10 p-4 text-sm text-accent">
                V1 is intentionally focused: Modrinth + Fabric + exportable config
                generation.
              </div>
            </div>

            <div className="grid gap-3">
              {steps.map((step, index) => (
                <div
                  key={step}
                  className="flex items-start gap-4 rounded-2xl border border-white/10 bg-white/[0.03] p-4"
                >
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl border border-accent/25 bg-accent/10 text-sm font-mono text-accent">
                    0{index + 1}
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-white">{step}</p>
                    <p className="mt-1 text-sm text-text-secondary">
                      {index === 0
                        ? "Start inside the Modrinth desktop app."
                        : index === 1
                          ? "Create a new instance from the app's instance flow."
                          : index === 2
                            ? "Use the file import option instead of building manually."
                            : index === 3
                              ? "Choose the JSON export generated by Pure FPS."
                              : "Jump straight into your optimized Fabric setup."}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
